{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <pytest1.test_class.TestClass object at 0x10a75ac50>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_class.py:9: AssertionError"}, "start": 1618111711488, "stop": 1618111711488, "uuid": "6cd0e35d-c9c8-4c64-97bc-5564e237312c", "historyId": "cca081f1c320efa44fffe5d884236360", "testCaseId": "9e2269e6af13cd7747e18ca37f3d74ba", "fullName": "test_class.TestClass#test_two", "labels": [{"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "77635-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class"}]}