{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <pytest1.test_class.TestClass object at 0x102945350>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_class.py:9: AssertionError"}, "start": 1618113660877, "stop": 1618113660878, "uuid": "c0145757-b009-403c-823d-2bd68ddcb64f", "historyId": "cca081f1c320efa44fffe5d884236360", "testCaseId": "9e2269e6af13cd7747e18ca37f3d74ba", "fullName": "test_class.TestClass#test_two", "labels": [{"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "78201-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class"}]}